### ISSUE TITLE
Create an option that allows the download of important info as file text

### ISSUE THREAD

**Issue by jordan-martins** [cms-PdmV/Stats2#14]
I would like to request the creation of a new feature in the tool that once one searches for relevant information, one can download all the workflows or input with the output datasets, for example.

A case:
In [here](https://cms-pdmv-prod.web.cern.ch/stats?processing_string=ECAL_R_HCAL_DI_JMENano), I am looking for all the information related to a `processing_string=ECAL_R_HCAL_DI_JMENano`. It would be useful to have somewhere in the page, a button where I could automatically have all the workflows that were used to produce the output datasets. In addition, it would be good to have information on input and output datasets. These are valuable information for PdmV ops regarding computing, providing helpful information that can boost PnR Ops and support fast turnaround workflows. If you find it more accessible, maybe a markdown table file with all the info like: `Name` | `input dataset` | `output dataset.`

Best,
Jordan

**Comment by vlimant** [comment]
following up this, @jordan-martins can you please retrieve a hand full of stats entries in a json and provide a markdown formatted table of the info that you'd like. and we take it from there

**Comment by ggonzr** [comment]
I have deployed a proposal under development: [Example](https://cms-pdmv-dev.web.cern.ch/stats?processing_string=ECAL_R_HCAL_DI_JMENano). @jordan-martins please let me know if it meets the requirement or if more fields or information are required.

**Comment by jordan-martins** [comment]
Hi @ggonzr ,
Sorry for taking so long to get back to us on this.
The solution is fantastic!
Thanks so much,
Jordan

**Comment by ggonzr** [comment]
Update shipped to both Stats2 environments. Closing this
